### ISSUE TITLE
Чому по обидві сторони змінної "х" потрібно ставити знак "+", щоб працював код?

### ISSUE THREAD

**Issue by denys991** [redexp/geekhub-2016-js#4]
``` javascript
$('#center').on('click', function (event) {
        var x = Math.ceil($('li').length / 2);
        console.log(x);
        $('li:nth-child('+ x +')').after('<li>3333</li>');
    });
```

**Comment by IuriiGrytsaienko** [comment]
ти в селектор повинен передати string. $('string'), а х в тебе просто змінна. для того, щоб отримати до неї доступ ти повинен зробити конкатенацію. 
те саме, що і 
var x = 10;
console.log('I have ' + x + 'apples')

**Comment by redexp** [comment]
@denys991 ты думал что должно работать вот так ?

``` javascript
$('li:nth-child('x')').after('<li>3333</li>');
```

нет, так нельзя писать, что бы получить новую строку ты должен использовать `+` как @IuriiGrytsaienko написал. Более того, на экзамене же был вопрос кода мы объявляли пустую строку и плюсовали к ней единицы и получали строку из кучи единиц

``` javascript
var x = '';
for (var i = 0; i < 10; i++) {
  x += 1;
}
console.log(x); // '1111111111'
```

первый класс вторая четверть Денис....

**Comment by denys991** [comment]
Дякую за відповідь, я не "учений", я тільки учусь, тому можу задавати періодично "глупі" запитання.

**Comment by redexp** [comment]
@denys991 всё правильно
