### ISSUE TITLE
Незрозумілий принцип роботи setTimeout()  в поєднанні з each().

### ISSUE THREAD

**Issue by denys991** [redexp/geekhub-2016-js#7]
Є така задача:
Даны текстовые инпуты. Первому поставьте текст 1, через секунду второму поставьте текст 2, еще через секунду третьему текст 3 и так далее.

Я її зробив таким чином і все працює:
``` javascript
$('input').each(function (i, elem) {
    setTimeout(function() {
        $(elem).val(i+1);
    }, i*1000);
})
```

Але не зрозуміло чому не працює без примноження часу затримки на ```i```?
І чи є більш раціональні прийоми використання ```setTimeout()``` з ```each() ```?

**Comment by IuriiGrytsaienko** [comment]
можна спробувати так, але я ще не придумав, як вигребти з масиву окремі елементи в циклі
так лічильник ніби очевидніше працює, але покищо для всіх однаково

``` javascript
$(document).ready(function(){
  var i = 1;
  var arr = $('input');
  var timer = setInterval(function(){
    $('input').val(i++);
    if (i > arr.length) { clearInterval(timer);}
  }, 1000);
});
```

**Comment by redexp** [comment]
Пацы, рано, немедля вернулись к тем задачам которые я вам дал, а не которые вы сами себе понаходили в инете

**Comment by denys991** [comment]
ок, це завдання з теми  : `кому важко придумувати завдання з jquery #5`
